---
title: "WD Proposed Sampling Sites"
author: "Chris Madsen"
date: "`r Sys.Date()`"
output: html_document
---

## Description: 

This script produces a map and interactive table of proposed sampling sites, V2. This document was produced on `r format(Sys.Date(),"%B %d, %Y")`.

<br>
<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = F)
#libraries
library(crosstalk)
library(tidyverse)
library(sf)
library(openxlsx)
library(bcdata)
library(basemaps)
library(DT)
library(ggspatial)
library(leaflet)

# Split the parks Canada dots into a whole separate layer, better colour, new legend saying "Parks Canada Sampling Locations", also add to the layerControl widget.

# we'll want to add some text that explains how this was done.
```

```{r get_data}

setwd(here::here())

# Load in data
ss = read.xlsx('data/2024 Sampling Sites_DRAFT1.xlsx', sheet = 'Mapping_locations') |>
  tidyr::as_tibble() |>
  purrr::set_names(snakecase::to_snake_case)

# Alouette is in a different CRS. Convert.
al = ss |> 
  dplyr::filter(str_detect(location_1,'Alouette'))

al = al |> 
  sf::st_as_sf(coords = c('easting','northing'), crs = 26910) |> 
  sf::st_transform(crs = 3005)

# delete_row = which(ss$region == 'OLD')
# 
# ss = ss |>
#   dplyr::slice(1:(delete_row-1))

# Spatialize the sampling site table; reproject to BC Albers.
ss = ss |>
  dplyr::filter(!str_detect(location_1,'Alouette')) |> 
  st_as_sf(coords = c("easting","northing"), crs = 2955) |>
  sf::st_transform(crs = 3005)

ss = dplyr::bind_rows(ss, al)

sample_bbox = st_bbox(st_buffer(st_as_sfc(sf::st_bbox(ss)), 10000))

if(!file.exists('data/interactive_sampling_V2_data/ws.gpkg')){
  
  # Get watersheds in area.
ws = bcdc_query_geodata('freshwater-atlas-watershed-groups') |>
  filter(INTERSECTS(ss)) |>
  collect()
  
  sf::write_sf(ws, 'data/interactive_sampling_V2_data/ws.gpkg')
} else {
  ws = sf::read_sf('data/interactive_sampling_V2_data/ws.gpkg')
}

ws_borders = ws |>
  dplyr::summarise()

ws_borders_s = rmapshaper::ms_simplify(ws_borders)

if(!file.exists('data/interactive_sampling_V2_data/big_rivers_in_ws.gpkg')){
# Nab large rivers in that area.
big_rivers_in_ws = bcdc_query_geodata('freshwater-atlas-stream-network') |> 
  bcdata::filter(STREAM_ORDER > 5) |> 
  bcdata::filter(INTERSECTS(ws_borders_s)) |> 
  collect() |> 
  sf::st_zm()

big_rivers_in_ws = big_rivers_in_ws |> 
  dplyr::group_by(GNIS_NAME, BLUE_LINE_KEY, STREAM_ORDER) |> 
  dplyr::summarise() |> 
  dplyr::ungroup()

big_rivers_in_ws = sf::st_transform(big_rivers_in_ws, 4326)

sf::write_sf(big_rivers_in_ws, 'data/interactive_sampling_V2_data/big_rivers_in_ws.gpkg')
} else {
  big_rivers_in_ws = sf::read_sf('data/interactive_sampling_V2_data/big_rivers_in_ws.gpkg')
}

# Map bbox based on watershed shapes.
map_bb = st_bbox(ws_borders)

ss = sf::st_transform(ss, 4326)

# Separate Parks Canada points from ss
# pc = ss |> dplyr::filter(priority == 'Park Canada')

# ss = ss |> dplyr::filter(priority != 'Park Canada')

```

```{r make_crosstalk_object}
# Make crosstalk object for ss
ss_shared = SharedData$new(ss)
```

```{r make_map}

ws_colour = leaflet::colorFactor(palette = 'Dark2',
                               domain = ws$WATERSHED_GROUP_NAME)

ss_method = leaflet::colorFactor(palette = 'Spectral',
                               domain = ss$method)

l = leaflet(elementId = 'map',
            height = 800, width = 1000) |>
  addTiles(group = 'Streets') |>
  leaflet::addMapPane(name = 'watersheds', zIndex = 200) |> 
  leaflet::addMapPane(name = 'rivers', zIndex = 300) |> 
  # leaflet::addMapPane(name = 'Parks_Canada', zIndex = 400) |> 
  leaflet::addMapPane(name = 'sample_sites', zIndex = 500) |> 
  addProviderTiles(provider = providers$OpenTopoMap,
                   options = providerTileOptions(opacity = 0.5),
                   group = 'Topography') |>
  addLayersControl(
    position = 'bottomright',
    baseGroups = c('Streets','Topography'),
    overlayGroups = c('watersheds','large rivers','sample sites'),
    options = layersControlOptions(collapsed = F)
  ) |> 
  addScaleBar('bottomleft') |>
  leaflet.extras::addResetMapButton()

l = l |> 
  addPolygons(
    weight = 1,
    data = st_transform(ws, 4326),
    label = ~paste0("Watershed: ",WATERSHED_GROUP_NAME),
    color = ~ws_colour(WATERSHED_GROUP_NAME),
    fillColor = ~ws_colour(WATERSHED_GROUP_NAME),
    fillOpacity = 0.20,
    options = pathOptions(pane = 'watersheds'),
    group = 'watersheds'
  ) |>
  addPolylines(
    data = big_rivers_in_ws,
    label = ~paste0("River: ",GNIS_NAME),
    weight = ~(STREAM_ORDER/5)^2,
    color = 'darkblue',
    opacity = 0.75,
    options = pathOptions(pane = 'rivers'),
    group = 'large rivers'
  ) |> 
  addCircleMarkers(
    data = ss_shared,
    label = ~paste0("Sampling Location: ",location_1," (",location_2,")"),
    radius = 5,
    weight = 1,
    color = 'black',
    fillColor = ~ss_method(method),
    opacity = 1,
    fillOpacity = 0.8,
    options = pathOptions(pane = 'sample_sites'),
    group = 'sample sites'
  ) |>
  # # Add Parks Canada points
  # addCircleMarkers(
  #   data = pc,
  #   radius = 5,
  #   weight = 1,
  #   color = 'black',
  #   fillColor = '#DB9',
  #   opacity = 1,
  #   fillOpacity = 0.8,
  #   options = pathOptions(pane = 'Parks_Canada'),
  #   group = 'Parks Canada'
  # ) |> 
  addLegend(title = "Watersheds",
            position = 'topright',
            pal = ws_colour,
            values = ws$WATERSHED_GROUP_NAME) |> 
  # addLegend(title = "Parks Canada Sampling Locations",
  #           position = 'bottomleft',
  #           colors = "#DB9", 
  #           labels = "") |> 
  addLegend(title = "Sample Method",
            position = 'bottomleft',
            pal = ss_method,
            values = ss$method)
```

## Map 

```{r print_map, out.width=1000, out.height=800}

method_filters = crosstalk::filter_checkbox(
    id = 'method_f', 
    label = 'Method Filters',
    sharedData = ss_shared,
    ~method,
    inline = F)

priority_filters = crosstalk::filter_checkbox(
    id = 'priority_f', 
    label = 'Priority Filters',
    sharedData = ss_shared,
    ~priority,
    inline = F)

delivery_filters = crosstalk::filter_checkbox(
  id = 'delivery_f',
  label = "Delivery Filters",
  sharedData = ss_shared,
  ~delivery,
  inline = F
)

l
```

```{r print_crosstalk_boxes}
bscols(
  widths = c(5,4,3),
  method_filters,
  delivery_filters,
  priority_filters
)
```

<br>

(Note: If no check-box is selected for a given variable, all levels of that variable in the data will be plotted.)

<br>
<br>
<br>

## Interactive Table

```{r interactive_dt,  out.width="1200px", out.height = "600px"}
DT::datatable(ss |> 
                # dplyr::bind_rows(pc) |> 
                sf::st_drop_geometry(),
              options = list(
                'pageLength' = '16'
              ))
```

